# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wtoken',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
