# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-03 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20180803_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'pwd')]),
        ),
    ]
